# Generated by Django 3.1 on 2021-03-08 20:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("microblog", "0004_auto_20210308_2018"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=20), default=list, size=None
            ),
        ),
    ]
