# Generated by Django 3.1 on 2021-03-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("microblog", "0005_auto_20210308_2019"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.URLField(default=1),
            preserve_default=False,
        ),
    ]
