# Generated by Django 3.1 on 2021-03-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("microblog", "0006_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="description",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
