# Generated by Django 3.1 on 2021-05-18 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("microblog", "0007_post_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="to_read",
            field=models.ManyToManyField(
                related_name="ToRead", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="ReadingList",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "to_read",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="microblog.post"
                    ),
                ),
            ],
        ),
    ]
